{% set name = "adorn" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adorn-{{ version }}.tar.gz
  sha256: 24fb41a55413bc8b6402c7c58c7bc2c6c0261cb19edaea529fd63cd44fdfa3b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry >=1.1,<2.0
  run:
    - python >=3.6,<4.0
    - pyyaml >=6.0.0,<7.0.0
    - tomli >=2.0.1,<3.0.0

test:
  imports:
    - adorn
    - adorn.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyadorn/adorn
  summary: Adorn
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jameswinegar
    - jacobBaumbach
