{% set name = "adorn" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adorn-{{ version }}.tar.gz
  sha256: 082e656ed7bea3b1292b58fc360b98f8b5aad402250dfc5602c742ff85390d24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry >=1.1,<2.0
  run:
    - python >=3.6,<4.0
    - typing-extensions >=4.0.1,<5.0.0

test:
  imports:
    - adorn
    - adorn.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyadorn/adorn
  summary: Adorn
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jameswinegar
    - jacobBaumbach
